name: Angular-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Septup NodeJs
      - name: septup nodejs
        uses: actions/setup-node@v4.0.1
        with:
          node-version: "18"

      # Install dependencies
      - name: Install deps
        run: |
          cd $GITHUB_WORKSPACE/hairdresser
          npm i
      
      - name: Setup Environment Directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/hairdresser/src/environments
      
      - name: Verify Environment Directory
        run: ls -la $GITHUB_WORKSPACE/hairdresser/src/environments
        
      - name: Copy Environment Files
        run: |
          echo "export const environment = {" > $GITHUB_WORKSPACE/hairdresser/src/environments/environment.ts
          echo "  production: false," >> $GITHUB_WORKSPACE/hairdresser/src/environments/environment.ts
          echo "  apiUrl: ''" >> $GITHUB_WORKSPACE/hairdresser/src/environments/environment.ts
          echo "};" >> $GITHUB_WORKSPACE/hairdresser/src/environments/environment.ts

          echo "export const environment = {" > $GITHUB_WORKSPACE/hairdresser/src/environments/environment.prod.ts
          echo "  production: true," >> $GITHUB_WORKSPACE/hairdresser/src/environments/environment.prod.ts
          echo "  apiUrl: '${{secrets.BACKEND_URL}}'" >> $GITHUB_WORKSPACE/hairdresser/src/environments/environment.prod.ts
          echo "};" >> $GITHUB_WORKSPACE/hairdresser/src/environments/environment.prod.ts
        
      - name: Debug Info
        run: |
          ls -la $GITHUB_WORKSPACE/hairdresser/src/environments/
          
      # Build app production
      - name: build app bundle
        run: |
          cd $GITHUB_WORKSPACE/hairdresser
          npm run build:prod

      # Deploy to GitPages
      - name: deploy to pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: $GITHUB_WORKSPACE/hairdresser/dist/hairdresser
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
