name: Angular-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Working Directory
        run: cd $GITHUB_WORKSPACE/hairdresser

      - name: Setup NodeJs
        uses: actions/setup-node@v4.0.1
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Copy Environment Files
        run: |
          echo "export const environment = {" > src/app/environments/environment.prod.ts
          echo "  production: true," >> src/app/environments/environment.prod.ts
          echo "  apiUrl: '${{secrets.BACKEND_URL}}'" >> src/app/environments/environment.prod.ts
          echo "};" >> src/app/environments/environment.prod.ts

      - name: Build Production
        run: npm run build:prod

      - name: Deploy to GitPages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: dist/hairdresser
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
